# CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: cd client && npm install && npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Migrate db using sequelize-cli:
      - run: npm config set prefix ~/.local
      - run: PATH=~/.local/bin/:$PATH
      - run: npm install -g sequelize-cli
      - run: mv migrations-ci/* migrations/
      - run: ./migrate-dev-db.sh
      - run:
          name: starting node server
          command: npm start && sleep 10
          background: true

      - run: npm test
